# Não especificamos mais uma imagem. Deixaremos o Gitpod usar a padrão.
tasks:
  - name: Install Dependencies & Init Mage
    init: |
      pip install mage-ai pandas google-cloud-storage
      python -m mage_ai init mage_project
    command: python -m mage_ai start mage_project

ports:
  - port: 6789
    onOpen: open-preview
